github: [metadata]

plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes"

title: Vision
search: true
search_full_content: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
