github: [metadata]

plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes"

title: Vision

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
